### ISSUE TITLE
✨ 돌보미 관련 API 개발

### ISSUE THREAD

**Issue by Juye0nLee** [9oormthon-univ/2024_DANPOONG_TEAM_15_BE#47]
## 💡 About
돌보미 관련 API 개발

## 📝 To Do
- [x] [돌봄 활동 공고 화면] 신청 목록 조회
- [ ] [돌봄 활동 공고 화면] 신청 상세 조회
- [ ] [돌보미 메인화면] 매칭된 돌봄 조회

## ✅ Issue check list
- [ ] Assignees, Labels 확인하기

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Implement new endpoints in ApplyController for caregiver-related functionality, including listing matched care activities and viewing care activity details. Update ApplyService and ApplyRepository to support these new features.

You can review changes in this commit: https://github.com/lkilu6456546/9oormthon-univ-2024_DANPOONG_TEAM_15_BE-47/commit/e1acc8e126b6a7d7525e65494db48ecb6ac94db1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
